#!/bin/sh
#
# Starts at daemon
#

umask 077

# Source function library.
. /etc/init.d/functions

PID=/var/run/cannelloni.pid
# SOCK=/tmp/mqttservice.socket

start() {
	echo -n "Starting cannelloni: "
        if [ -f "${PID}.lock" ]; then
                echo "SKIP"
        else
                cannelloni -I can0 -p > /var/log/cannelloni 2>&1 &
                echo "OK"
        fi
}
stop() {
	echo -n "Stopping cannelloni: "
	killall cannelloni 2> /dev/null
	if [ $? -eq 0 ]; then echo "OK"; else echo "SKIP"; fi
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  status)
	status cannelloni
	;;
  *)
	echo $"Usage: $0 {start|stop|restart|status}"
	exit 1
esac

exit $?

